### ISSUE TITLE
Feature Request: Membership FAQs on Account pages

### ISSUE THREAD

**Issue by kassanj** [wherebyus/general-tasks#1026]

**Comment by kassanj** [comment]
Alexandra   [3 hours ago]
all good. here’s the copy: https://docs.google.com/document/d/1gIFxX7FZePn4Sokas5jm1H-ha8dTfUJHIGu-42ZTFbI/edit?usp=sharing

slytherfield   [3 hours ago]
So yeah if it's in the dashboard then I think "My Membership" makes the most _sense_. That actual page (if you look at the url) goes to some subscription template that is auto-generated, so we'd probably need to figure out how to get it there. We have several tickets related to giving this whole section some TLC (e.g., we've been able to change the title to "my membership" in the menu but the template shows "subscription #12344".

**Comment by kassanj** [comment]
Copy

Tips on your membership

What exactly does my [brand] membership get me?
Discounted tickets to our events. A welcome kit with cool brand swag. Extra content, like trivia games for prizes. Access to exclusive giveaways. And maybe most importantly: the warm, fuzzy feelings that come with supporting your fave local newsletter. Your support helps us all create more awesome stories and events together. We work with and for you to build this little slice of community in [city]. And the work gets stronger with your ideas, feedback, connections, and financial support.

How do I get my member perks?
Your member perks are delivered to you right in your daily [brand] newsletter. You’ll see a slightly different version of the newsletter, that includes your event discounts, giveaway opportunities, and some fun extra content. And we ship swag every few months. You can update your address to the left under “Addresses.” 

When am I billed?
Monthly or annually, depending on the option you chose when you purchased your membership. We’ll send you an email a few days before your next payment date (noted below) so you don’t get any surprise charges from us. Pro tip: monthly billing helps us most because it gives us scrappy startup folks a better way to predict revenue. 

I have an idea or question. How do I share it with you?
Drop us a note at hello@[brand].com.

**Comment by kassanj** [comment]
### QA Notes
1. Go to https://miami.wbudevelop.wpengine.com/my-account/ and login.
2. Click on the `My Membership` tab.
EXPECT: All the copy found above (Tips on your membership) to render on the page right above `Subscription Totals`. 
EXPECT: The copy to be dynamic. (The New Tropic, Miami, hello@thenewtropic.com)

**Comment by carogea** [comment]
@kassanj looks good but should this be a paragraph instead of bullets?

![Screen Shot 2019-03-28 at 1.36.24 PM.png](https://images.zenhubusercontent.com/5c630d90c95c1c66f2b87ae3/9b0f4e6b-ff9d-4f7c-951b-c23f313d619e)

**Comment by michaelschofield** [comment]
This passes *technical* QA for me, but I moved it to awaiting sign off so @carogea and @alexandraleighs can give it the thumbs-up or ask for revisions.

**Comment by michaelschofield** [comment]
@carogea This is ready for your eyes again, I believe.

**Comment by carogea** [comment]
looks good
