### ISSUE TITLE
wherebyEventUserPropertyUpdated_referralCount consistently times out

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1032]
## Feature or problem
`wherebyEventUserPropertyUpdated_referralCount` seems to consistently timeout. Investigate.

### Reproduction

![image](https://user-images.githubusercontent.com/33945/55372097-830a5780-54ce-11e9-8077-12c2039ec2bd.png)

https://thenewtropic.com/wp-admin/tools.php?page=action-scheduler&orderby=schedule&order=desc&s=wherebyEventUserPropertyUpdated_referralCount&action=-1&action2=-1&status=failed

In scheduled actions, you can see that most of the "Failed" actions are timeouts. We should investigate this event and the controller method it calls to see if there are any obvious reasons.

This is important because this needs to be consistent if we want to add user's referralCount to the newsletter.

### Suggested priority
priority-high

### Stakeholders
*Submitted:* michael

### Definition of done
How will we know when this feature is complete?

**Comment by ErnieAtLYD** [comment]
> If an action runs for more than 5 minutes, Action Scheduler will assume the action has timed out and will mark it as failed. **However, if all callbacks attached to the action were to successfully complete sometime after that 5 minute timeout, its status would later be updated to completed.**

as well as:

> By default, Action Scheduler will only process actions for a maximum of 30 seconds. This time limit minimises the risk of a script timeout on unknown hosting environments, some of which enforce 30 second timeouts.
>
> If you know your host supports longer than this time limit for web requests, you can increase this time limit. This allows more actions to be processed in each request and reduces the lag between processing each queue, greating speeding up the processing rate of scheduled actions.
>
> For example, the following snippet will increase the timelimit to 2 minutes (120 seconds):
```js
function eg_increase_time_limit( $time_limit ) {
	return 120;
}
add_filter( 'action_scheduler_queue_runner_time_limit', 'eg_increase_time_limit' );
```
> Some of the known host time limits are: 60 second on WP Engine, 120 seconds on Pantheon, 120 seconds on SiteGround

**Comment by michaelschofield** [comment]
Hmm. I think the return value on the method this is returning is wrong, or something's broken. It never completes - when I force "run" it it returns a malformed JSON response.

![image.png](https://images.zenhubusercontent.com/5907891d51aa2c30577cf4d5/7b1990a2-723d-4b9a-bddb-770d5e4c646e)

**Comment by michaelschofield** [comment]
So I made a code tweak to the methods that event is triggering so they return a `bool` instead of a JSON response. Let's see if that does it.
