### ISSUE TITLE
Design a WP Offload SES launch plan 

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1036]
## Feature or problem
See [Dropbox Paper document](https://paper.dropbox.com/doc/AWS-SES-transactional-email-strategy--AaflX7qmwhju0PYGT0Psw8ktAg-0PxZducJnXjKlRVgWgr01) which has been sent to Membership, LDs and Event teams.

### Suggested priority
priority-high

### Stakeholders
*Submitted:* michael

### Definition of done
A series of GitHub issues which illustrates what is necessary to launch WP Offload SES.

**Comment by ErnieAtLYD** [comment]
Done, as I wrote out #1097.
