### ISSUE TITLE
Email design: On Gmail, gray background should be 100% panel width

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1042]
![image.png](https://images.zenhubusercontent.com/5b3b8639fc589b1d091c443c/07e11d6d-e50f-4e13-8f1d-bd8fb255ae5e)

Open up a newsletter in GMail on your browser. I'm using a Mac.
EXPECTED: the gray background should be 100% of the mail content panel
ACTUAL: the gray background is only seen as padding in the content boxes

Notes: Don't want to use tables as a fix acc to Schofield

**Comment by ErnieAtLYD** [comment]
Schofield: "oh that was when I moved everything that wasn't prioritized back to New so that CG could prioritize them We then prioritized it so it should have gone back to Backlog."

**Comment by michaelschofield** [comment]
I don't think we're going to get to this guy so I'm moving it back to backlog.
