### ISSUE TITLE
Storing a MailChimp web ID when creating a campaign ID

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1047]
## STORY
When the Newsletter Builder is creating a newsletter
AND it's generating a new MailChimp campaign ID,
WE WANT the builder app to also **generate a MailChimp web ID**
SO THAT we can build a link to the MailChimp Member Preview URL
AND a link to the MailChimp campaign reporting URL

## DOD
 - A MailChimp web ID is created when the campaign ID is created
 - A MailChimp web ID is edited when a campaign ID is edited
 - If the user blanks out the campaign ID by hand, the MailChimp web ID should become blank

**Comment by michaelschofield** [comment]
Confirmed that this key exists on a newsletter in phpmyadmin.
