### ISSUE TITLE
Titles overlap images on homepages

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1050]
## Feature or problem
Describe the feature or problem here.

### Reproduction
On TEG.com.

### Actual behavior
One line is cut over the image

### Suggested expected behavior
For headlines to be readable all the way through on the sidebar

### Suggested priority
priority-high

### Stakeholders
*Submitted:* moniguzman

### Definition of done
How will we know when this feature is complete?

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [ ] Brew the coffee

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code ()
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing ()
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check

**Comment by michaelschofield** [comment]
This is a duplicate of #987.

**Comment by carogea** [comment]
![Screen Shot 2019-03-29 at 2.38.49 PM.png](https://images.zenhubusercontent.com/5c630d90c95c1c66f2b87ae3/fa6aa615-bae5-4804-98a3-391b186033c7)

**Comment by michaelschofield** [comment]
## QA
1. Confirm on each homepage that the secondary stories titles do not overlap with the image.
