### ISSUE TITLE
Hiring a contractor for data work

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#1058]
DOD: Hiring a contractor for data analysis work

Note: This is a task for Rebekah as well

**Comment by rebekahmonson** [comment]
hi there

**Comment by ErnieAtLYD** [comment]
- Had status meeting 4/12
 - Rebekah to finalize all the paperwork

**Comment by michaelschofield** [comment]
@ErnieAtLYD Is this done now that we've got CP on board?
