### ISSUE TITLE
Scope of work for aggregate service 

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#1059]
DOD: get a scope of work for aggregate service

**Comment by kassanj** [comment]
@michaelschofield and I discussed the following document and created a plan of action. 

https://paper.dropbox.com/doc/Aggregate-Microservice--AajGsTalCJvU0jSwUyA8CCWhAQ-UMRcfwPHwmryROssUZ79W

To-Do  (32 - 35 points)
- Revisit Aggregate schema knowing its not part of WordPress - 2
- Research how to set up AWS SQL Database, servers, costs - 5
- Research DevOps maintenance costs, skillset - 5
- Make final decision - 5
- Build AggregateService repo, model, dtos, CRUD, controllers, routes, connections, off - 15
