### ISSUE TITLE
Download all leads out of Hearken (PIT's) before the contract and our access ends. 

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1060]
## Feature or problem
The Incline's access to Hearken will be ending soon -- Mayish, Brian Boyer thinks -- so we want to download all leads out of Hearken before our access to it ends.

See this thread: https://wherebyus.slack.com/archives/CH1RSL4B1/p1553889704052300

### Stakeholders
* @alexandraleighs

### Definition of done
We will have a spreadsheet (e.g., an airtable) with all of the leads downloaded from Hearken.

This has to be done by April 30

**Comment by ErnieAtLYD** [comment]
the incline's contract w hearken ends april 30.

**Comment by michaelschofield** [comment]
@alexandraleighs Hey there. Do we have everything we need out of Hearken? If so I can close this ticket.

**Comment by alexandraleighs** [comment]
one outstanding item from Pulptown. Pinged Katie this morning.

**Comment by alexandraleighs** [comment]
ok confirmed we have everything exported. closing.
