### ISSUE TITLE
Scope newsletter template building

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1062]
Assess and scope the work required to automatically compile the newsletter template.

### Suggested expected behavior
A solution and scope of work. 

### Suggested priority
priority-medium

### Definition of done
A solution and scope of work

**Comment by ErnieAtLYD** [comment]
Related to #953

**Comment by michaelschofield** [comment]
I created the following ticket with subtasks: https://app.zenhub.com/workspaces/tech-team-repos-5b3b863cf36bf13b2ad5b66e/issues/wherebyus/newsletterservice/6
