### ISSUE TITLE
Photos can stretch in NL (Gmail app on iPhone)

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#1068]
## Reproduction steps
Open April 1 non-member version of The New Tropic in Gmail app on iPhone

## Expected
Image loads proportionally

## Actual
Non-members photo stretched because the image height was hard-coded

## DOD
Image width and height are stripped from 'img' tags in newsletters

**Comment by carogea** [comment]
![Screen Shot 2019-04-01 at 11.12.24 AM.jpg](https://images.zenhubusercontent.com/5c630d90c95c1c66f2b87ae3/9cf61e08-f3c0-4c80-9032-c0302c888317)

This is in the non-member version of The New Tropic on April 1st, viewed in Gmail on iPhone. Code below:

```<img class="aligncenter wp-image-268573 size-full" src="https://thenewtropic.com/wp-content/uploads/sites/2/2015/05/IMG_2377-1.jpg" alt="" width="600" height="667" />```

**Comment by michaelschofield** [comment]
## QA
1. Add an image to the editor from the library and confirm that neither width nor height attributes copy into the editor
2. Send a test email and confirm in Gmail for iOS that no images in the WYSIWYG's compress and stretch oddly.
