### ISSUE TITLE
Prototype low-hanging fruit options to bring the content team behind a newsletter forward, to make it even more human.

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1072]
The desired impact is that the user would more easily attach to the person or persons behind a piece of content. Think low-hanging fruit, like bylines, avatars, bios, etc. 

From Caro: I was also talking to Rebekah recently about adding more "fun" to newsletters, we should consider these 2 things together

**Comment by ErnieAtLYD** [comment]
@michaelschofield are you thinking like an ideation thing? A hackweek? Something similar? @carogea and I were talking about this during our 1:1s.
