### ISSUE TITLE
PIT Migration Phase 2: Newsletter builder

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1074]
## DOD

- A newsletter builder is specifically created under the `wbu` WP Engine multisite
  - PIT editors could in theory, still update web content through theincline.com, but they would write their newsletters somewhere else.
- 💵 Pittsburgh is added inside the Promo app
- 📩 PIT editors can start building newsletters using the newsletter builder

**Comment by michaelschofield** [comment]
Just moved back to SB, since individual tasks in this epic are In Progress but not all tasks at once are in progress, and blah blah blah. Just uncomplicating the In Progress pipeline
