### ISSUE TITLE
Decide whether or not we want to have a communications plan when their newsletter changes (we will have one for the website)

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1075]
DOD: Yes or no
If yes, how will we enact it

**Comment by carogea** [comment]
Decided yes, documented here https://docs.google.com/document/d/10vnEWPHqIKJ1YkQg2ZdWF3xmd01HuEYKcNbgXdcC1gc/edit?usp=sharing
