### ISSUE TITLE
Pittsburgh sub-site is created under wbu’s WPE account

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1076]
Just creating Pittsburgh sub-site on dev

DOD: We would be launching pittsburgh.wbu.wpengine.com

theincline.com will not change yet

**Comment by kassanj** [comment]
Encountered some configuration issues with wbudevelop, so i increased the estimate to 2.

### QA Notes

Check if The Incline subsites exist
Development -> https://pittsburgh.wbudevelop.wpengine.com/
Staging -> http://pittsburgh.wbu.staging.wpengine.com/
Production -> https://pittsburgh.wbu.wpengine.com (No longer available, this is deactivated for now)
