### ISSUE TITLE
Install Newsletter builder and WBA for PIT

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1077]
Trickier because there is now a newsletter dependency on wherebyapp

DOD: the newsletter builder is up and functioning and available for Pittsburgh editors; they are able to build a newsletter using it and send to a mailing list.

They do not need to *use* it next week, but it should be available

**Comment by kassanj** [comment]
### QA Notes
Develop -> http://pittsburgh.wbudevelop.wpengine.com/wp-admin/post-new.php?post_type=wbu_newsletter
Staging -> https://pittsburgh.wbu.staging.wpengine.com/wp-admin/post-new.php?post_type=wbu_newsletter
Production -> Disabled at the moment
