### ISSUE TITLE
Pittsburgh added inside Promo app

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1079]
DOD: Pittsburgh is added inside Promo app; the DOD will be everything but the screenshots

We do not want this to be visible to advertisers yet

This won't be available until they start using the builder to build all of their stuff

**Comment by kassanj** [comment]
### QA Notes

1. Go to https://promotions.whereby.us/pittsburgh
2. EXPECT: To see images with The Incline content
3. EXPECT: NO packages listed
4. Go to https://promotions.whereby.us/
5. EXPECT: The Incline NOT to be listed
