### ISSUE TITLE
Not seeing the ability to add an extra section in the Newsletter builder

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1086]
## Feature or problem
The additional optional section appears to be gone.

### Reproduction
It used to appear just under the Promo 3 spot and just above the member section.

### Actual behavior
The additional optional section appears to be gone.

### Suggested expected behavior
It should appear just under the Promo 3 spot, above the member section

### Suggested priority
~priority-critical~ Now medium

### Stakeholders
*Submitted:* lance

### Definition of done
How will we know when this feature is complete?

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [ ] Brew the coffee

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code ()
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing ()
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check

**Comment by ErnieAtLYD** [comment]
Thread on Slack is here: https://wherebyus.slack.com/archives/C63BGU20N/p1554242342145000

**Comment by ErnieAtLYD** [comment]
Follow up with Lance re: severity. Whoever gets to it first should remove the other from the assigned issue

**Comment by kassanj** [comment]
### QA Notes
1. Go to http://miami.wbudevelop.wpengine.com/wp-admin/edit.php?post_type=acf-field-group and sync newsletter fields
2. Add new Newsletter
3. *Expect*: Additional Section to appear under Promo #3 and before non-member Section
4. Add content to the Additional Section, and save
5. *Expect*:  Additional Section to render properly on preview. 
4. Send a test newsletter to yourself
5. *Expect*:  Additional Section to render properly on sent newsletter.
