### ISSUE TITLE
published articles not loading correctly on the incline wordpress

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1088]
## Feature or problem
Describe the feature or problem here.

### Reproduction
When we look at published articles on the incline's wordpress, it appears there is no text loading. upon highlighting, you'll see there *is* text there, but it's in html not rich text, as it usually is

### Suggested expected behavior
Please review the text fields in articles and restore the copy in rich text

### Suggested priority
priority-critical

### Stakeholders
*Submitted:* rossilynne

### Definition of done
How will we know when this feature is complete?

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [ ] Brew the coffee

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code ()
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing ()
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check

**Comment by ErnieAtLYD** [comment]
We were missing a MailChimp API in theincline.com's `wp-config.php` file. Without it the code breaks prematurely.
