### ISSUE TITLE
White Paper: Write a strategy for migrating CMB2 -> ACF Pro

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1090]
DOD: Write up of strategy for migrating CMB2 -> ACF Pro

via [Slack conversation](https://wherebyus.slack.com/archives/C63BGU20N/p1554304243153800?thread_ts=1554304176.151500&cid=C63BGU20N):
>ernie   [1 hour ago]
>To put on the need to do eventually list - a battle plan on how to handle future things related to ACF and CMB2 going forward
>
>schoeyfield   [1 hour ago]
>Word. I think CMB2 => ACF should be the first headscratcher. That would simplify things for us a lot.
>
>schoeyfield   [1 hour ago]
>I'm not in any hurry to ditch ACF just yet. It has its uses, but having two custom field managers is just a lot to remember. The first thing I'd like to do is start seeing what MailChimp calls we make in Newsletters and see if we can use MailChimpService for that, and just start whittling down places where we're duplicating

### References
 * [Using Advanced Custom Fields without frontend dependency](https://www.billerickson.net/advanced-custom-fields-frontend-dependency/)
 * [Importing serialized post_meta into ACF fields](https://support.advancedcustomfields.com/forums/topic/importing-serialized-post_meta-into-acf-fields/#post-50395)

**Comment by michaelschofield** [comment]
CMB2 is used widely by sponsor placement and nested articles. My thinking is that CMB2 is best replaced by attrition. I think the solution for the article is to create a custom `Article` post type that allows for nesting, and child articles, etc.
