### ISSUE TITLE
Make final decision on AggregateService

### ISSUE THREAD

**Issue by kassanj** [wherebyus/general-tasks#1103]
Answer could be yes, no, not now, not now depending on product decisions, etc...

**Comment by michaelschofield** [comment]
Made this a blocker to #1104 fyi.

**Comment by michaelschofield** [comment]
@ErnieAtLYD @kassanj Ya'll want to touch base on this? Probably will only take 15 minutes, but we could also do it async in slack.

**Comment by michaelschofield** [comment]
@ErnieAtLYD @kassanj I think we're on board with _doing_

* We can wait for our FB Accelerator-funded DO server
* Premortem: if we end up not using this or have to kill it, we determined that the time spent is great for leveling up.

**Comment by michaelschofield** [comment]
Created the Create AggregateService epic and sub tasks https://app.zenhub.com/workspaces/tech-team-repos-5b3b863cf36bf13b2ad5b66e/issues/wherebyus/general-tasks/1099
