### ISSUE TITLE
Audit Growth Tracking progress

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1109]
It's pretty clear we need to bring back the Growth Tracker, but we don't know what things are working and what things aren't. What do we need to do to get this back running again? Is it worth changing how metadata is stored (currently on MailChimp)? 

What do we need to track? What of this is not automated? What can we automate, and how? 

DOD: An action plan for growth tracking

https://paper.dropbox.com/doc/Growth-Tracker-V2--Aa~e5yRoI38UFlMHRoOBZoZfAg-p1FhqoWuqT9uvSxaN8lft

**Comment by carogea** [comment]
@ErnieAtLYD feel free to drop this back into sprint backlog and the milestone if you think this is something that will get done soon
