### ISSUE TITLE
Scope for adding Google Schema to appropriate newsletter & transactional emails

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1124]
https://developers.google.com/gmail/

DOD: A scope of work

**Comment by michaelschofield** [comment]
## Newsletter microdata
Gmail supports "Articles" markup (https://developers.google.com/gmail/markup/reference/article) which presents a slider of articles in the subject line. We would be able to do this but first we would have to implement aggregate and/or superaggregate specific fields that generate we would need to generate the proper data.

## Orders
Presuming we have template-level access to Orders and Invoices, we can add Orders markup https://developers.google.com/gmail/markup/reference/order into the`<head>` of the email.

## Events
When folks register for an event, presuming we have email level access, we can bake Events markup (https://developers.google.com/gmail/markup/reference/event-reservation) into the `<head>` of the email.
