### ISSUE TITLE
Come up with a non-jerky response if someone complains about email using an old client

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1132]
Via https://whereby.zendesk.com/agent/tickets/5498:
> Not sure if it’s possible to reply to this email address, but wanted to let you know that the desktop (vs mobile) experience with the newsletter is having some issues. See screenshot below. Hope this helps!

![image](https://user-images.githubusercontent.com/33945/55900168-971c1c00-5b94-11e9-860a-c1444ee87b88.png)

The client is MS Exchange but we should find a tactful way of saying "lol no we don't support exchange"

**Comment by rebekahmonson** [comment]
Doc: https://docs.google.com/document/d/1EI4HD-C273SPxo7aobu3qfGz06KOgOLwDPcp5Myy1Rc/edit
