### ISSUE TITLE
Draft Membership transfer communication plan for PIT

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1144]
USER COMMUNICATION: How do we communicate that theincline.com is now owned by WBU with a new format? Needs to take into account membership

DOD
- [ ] The copy

**Comment by alexandraleighs** [comment]
Here's the comms plan and draft copy — will need a slight edit with hyperlinks added before sending. https://docs.google.com/document/d/11OYxZ6fZgKtzJ9osg0yei2RARmGhJzlY2Fgb2tXgziI/edit?usp=sharing
