### ISSUE TITLE
Audit PIT Custom Post types

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1147]
We have a lot of customized WP objects; so do they. For sake of consistency and my sanity we will have to use our implementation, and ideally on a new WordPress build.

Do we want to carry any of this functionality over before Pit acclimates with our stack?

### DOD
 * We have audited all PIT custom post types.
 * For each post type, a business decision has been made for each:
   * Make the decision to Integrate it into WBU sites NOW
   * Make the decision to Integrate it into WBU sites EVENTUALLY
   * Draft up a migration plan if applicable
   * Do not integrate into WBU sites

**Comment by ErnieAtLYD** [comment]
Document started here: https://docs.google.com/document/d/1hJNrpB6jex0WIpefi_zBIUUvs3YjcPfCICDWhsjUSNA/edit#

**Comment by michaelschofield** [comment]
@carogea @ErnieAtLYD Hey fam. Before we close this, are there any follow-up steps -- like "create this post type" or "migrate this post type to a regular post" or "trash this post type" -- that need to be turned into tix on the board?

**Comment by carogea** [comment]
@michaelschofield i think just the story ticket for this week does the job

**Comment by carogea** [comment]
@michaelschofield info here. our post type we use for our other brands should do the job for the incline https://docs.google.com/document/d/1hJNrpB6jex0WIpefi_zBIUUvs3YjcPfCICDWhsjUSNA/edit#heading=h.w9ovoqejlnzt
