### ISSUE TITLE
Create an Incline logo with the same dimensions and positioning as the other logos, then replace the logo on the incline's sites.

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1156]
![image.png](https://images.zenhubusercontent.com/5907891d51aa2c30577cf4d5/8f8aad16-d9fd-48db-8e15-4b7088cc43d4)

The current logo is [properly] edge to edge, but our other brands' logos aren't. Unfortunately, the newsletter template is designed around those. We'll revisit proper edge-to-edge logos in another ticket, but in the meantime, we need to spin-up an Incline logo using those dimensions so that the newsletter doesn't look bonkers.

**Comment by kassanj** [comment]
I added padding to the logo on Staging and sent a test newsletter. (Images below)
![Screen Shot 2019-04-19 at 1.00.47 PM.png](https://images.zenhubusercontent.com/5b437bf5ce32d54e64eac4de/67a6e8a0-c5e9-434a-93d8-f34eda17b7f7)
![Screen Shot 2019-04-19 at 1.02.18 PM.png](https://images.zenhubusercontent.com/5b437bf5ce32d54e64eac4de/983c9382-1771-4d84-8275-06243f0467c0)
