### ISSUE TITLE
Add the Incline colors and logo added to meme.whereby.us

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1163]
## Feature or problem
Describe the feature or problem here.

### Reproduction
Please ensure it's possible to create a conversation starter card (see facebook examples) with the Incline's brand colors and logo. 

### Suggested priority
priority-low

### Stakeholders
*Submitted:* haley

**Comment by ErnieAtLYD** [comment]
Completed by Rebekah cuz she's a baller
