### ISSUE TITLE
Design system: convert rem back to pixels

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1168]
## How to approach this
Let's use the `font-size.yml` tokens as the reference, specifically the tokens that include the suffix `_fallback` as those are set as pixels. So we already know what the pixels _should_ be. Padding and margins are usually a fraction _larger_ than the font-size. So if our base font size is `21px` on large screens, our base _sizing_ size (for margins and padding_ is `27.2px`

Rather than rewrite a bunch of token files and maybe accidentally bork some designs, let's create a new token file.

### New tokens
- [x] Create a `sizing.yml` token file
- [x] We need the following new tokens for both `sm` screens and `md` screens.

```
sizing_sm_small: 14px;
sizing_md_small: 16px;
sizing_sm_base: 27.2px
sizing_md_base: 32px
```
Rather than swap our `padding` tokens in a whole bunch of components for `sizing` tokens, let's just update the chief culprits in the `padding.yml` token file and the `margin.yml` token file.
- [x]  Convert `padding.yml` values from `rem` to `px`, where `1rem` is 16px, `2rem` is 32px, etc.
- [x] Convert `margin.yml` values from `rem` to `px`, where `1rem` is 16px, `2rem` is 32px, etc.

## Original conversation
via @michaelschofield: 

![image](https://user-images.githubusercontent.com/33945/56312448-28a00680-611e-11e9-8bb6-142638dd35bb.png)

![image](https://user-images.githubusercontent.com/33945/56312461-2e95e780-611e-11e9-9489-224f906731e7.png)

I think what we can start with this ticket is, as anti-modern as it feels, start transitioning away from using `rem` and `em` but back to `px`.

The main reason is that if we want to truly create a design system that is cross email / browser, many email clients only respond to `px` or their reference to `rem` is a different unit than ours.

I can start creating `sizing` tokens that, as we iterate, we can transition to. The elegance here is that the padding value isn't an arbitrary `2rem`, but it's the exact size of an `h2` on both small screens and larger screens.

I actually don't know if it's better if margins/padding should correlate with body font size or not, but so far using h2, which itself is a multiplication of the body font size, doesn't look weird.

**Comment by michaelschofield** [comment]
Added notes about how to go about this ticket above. All the changes should be to the tokens, we shouldn't need to change any components.
