### ISSUE TITLE
Investigate replacing DIN Next Pro Medium with Adobe's DIN

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1169]
## Feature or problem
We currently have DIN Next Pro Medium, which we download and include manually. This also prevents us from using the font in email. Adobe now offers a DIN font that we may want to sub into our sites to save on webfont costs: https://fonts.adobe.com/fonts/urw-din

## Definition of done
- [x] A determination as to whether or not this is feasible and a follow-up ticket[s] to implement

### Suggested priority
priority-medium

### Stakeholders
*Submitted:* ernie

**Comment by ErnieAtLYD** [comment]
To use in HTML:
`<link rel="stylesheet" href="https://use.typekit.net/ndi8ykz.css">`

To use in email:
```
<style>
  @import url("https://use.typekit.net/ndi8ykz.css");
</style>
```

URW DIN Regular Italic
```
font-family: urw-din, sans-serif;
font-weight: 400;
font-style: italic;
```

URW DIN Regular
```
font-family: urw-din, sans-serif;
font-weight: 400;
font-style: normal;
```

URW DIN Medium Italic
```
font-family: urw-din, sans-serif;
font-weight: 500;
font-style: italic;
```

URW DIN Medium
```
font-family: urw-din, sans-serif;
font-weight: 500;
font-style: normal;
```

URW DIN Bold Italic
```
font-family: urw-din, sans-serif;
font-weight: 700;
font-style: italic;
```

URW DIN Bold
```
font-family: urw-din, sans-serif;
font-weight: 700;
font-style: normal;
```

**Comment by ErnieAtLYD** [comment]
Yeah, totally straightforward to do. Going to implement this into a ticket now.
