### ISSUE TITLE
build: update foundation-sites to 6.5.1, FoundationPress repo update

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1170]
## QA Notes
Make sure nothing visually breaks. This should also lesson the amount of npm vulnerabilities. 

### Make sure pull request has the following:
- [ ] The code has gone through a linter such as PHPCBF and/or `codeclimate analyze`
- [x] A QA case

**Comment by michaelschofield** [comment]
Unfortunately it looks like this update has enough breaking changes to really impact the look and feel. Screenshot below. Kassandra rolled this commit back on develop and confirmed that the theme looked normal afterward.

![image.png](https://images.zenhubusercontent.com/5907891d51aa2c30577cf4d5/609f4bcf-cfa6-4297-ace8-f875ab2c6f92)
