### ISSUE TITLE
investigate: Google Voice being available as a core G Suite service

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1174]
Hello Administrator,

Since our Beta Program announcement last year, we’ve been testing an enterprise-ready version of Google Voice. Over the next seven days, Google Voice will become available as a core G Suite service for all eligible* G Suite customers (additional fees apply to this new, managed version of Google Voice). This email will help you understand the transition details but you can also refer to the Voice webpage for more information.

What's changing: 
 - Managed Google Voice is available in 3 tiers and will become a core G Suite service for your domain after subscribing to a service tier.
 - Managed Voice accounts will be covered under your existing G Suite agreement and additional Google Voice service specific terms.
 - Support for managed Voice accounts will be the same as other G Suite core services.

What's not changing:
 - The Google Voice service will remain “on” by default.
 - If users in your domain signed up for Voice prior to this launch, they will be able to maintain their legacy unmanaged Voice subscriptions without additional cost, and will remain subject to the Google Voice consumer terms of service. You can add a Voice subscription and upgrade these users to managed Voice users in your Admin console.
 - Hangouts Meet (also a core G Suite service) is integrated with Google Voice, allowing meeting participants to dial in or be added by phone.

What do I need to do?
 - If you did not participate in the Google Voice Beta Program and would like to use Google Voice for your organization, [follow these steps](https://support.google.com/a/answer/9274402) to add a Voice subscription.

We’re here to help
 - If you have additional questions or need technical assistance, please contact Google support. When you call or submit your support case, reference issue number 129486277.

**Comment by michaelschofield** [comment]
This is: "Ernie needs to be a fuckin' IT manager."

**Comment by ErnieAtLYD** [comment]
It costs $10-30 per user, per month. That's just way too much even if we only gave access to LDs, and I'm fairly certain CKS would never go for this. I think the better option - if we care that much, and I don't think we do at the moment - is to use some sort of poor man's Twilio PBX replacement. But honestly I don't think we're there yet, as there just hasn't really been a pressing need to do this. Gonna close this.

**Comment by michaelschofield** [comment]
I agree 100%.
