### ISSUE TITLE
Guinea pig Incline membership migration

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#1181]
Also, get some early documentation on how to migrate to help us later.

## To do
 - [x] Someone to purchase a membership from theincline.com
 - [x] Share out user experience
 - [x] Try to migrate that membership from theincline.com's NRH membership to WBU's WooCommerce membership platform

**Comment by michaelschofield** [comment]
https://docs.google.com/spreadsheets/d/1IKVDYCzd1yc06Orc8yrphfHSWYhw6yPopEqYc1_QmrI/edit#gid=1678731467 

And my comment to Alexandra in slack:

> @Alexandra Hey there. So I successfully migrated an Incline member (me) into our system and the export/import process itself seems like it will be pretty painless. I doc'd it https://docs.google.com/spreadsheets/d/1IKVDYCzd1yc06Orc8yrphfHSWYhw6yPopEqYc1_QmrI/edit#gid=1678731467 but this is something tech can take care of. As predicted, nothing involved with capturing their order information will be transferred. Meaning that as they reach the expiration date of their Incline membership, they'll need to get Follow-up emails asking them to re-up. They will have to log in, and pay for a brand new membership. If they don't, they don't.

> I would suggest Incline-member specific copy for the membership expiration emails that re-explain the situation.
