### ISSUE TITLE
Touchup our content model spreadsheet to reflect current state

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1189]
"One thing I'd love to work with you on in a no-rush side-hustle way is to really marry your content _strategy_ to our content _models_. Right now we have quite a bit of disparity between content we make and how it's stored in the database. I think Q2 is a good time to start bringing them closer together, and can help us better make decisions about - like- whether _issues_ should be their own content type. If we have strong content models that marry strategy and infrastucture, it opens up a lot of options in terms of how content interacts with other content, content reuse and modularity, content-driven design features, etc."

Thread of info: https://wherebyus.slack.com/archives/C02GKL3KV/p1555769112007200?thread_ts=1555769112.007200

**Comment by carogea** [comment]
@michaelschofield could you flesh this out a little more as a ticket, noting the implications of this and maybe giving it an estimate?

**Comment by carogea** [comment]
@michaelschofield can you add a DOD and maybe a bit more explanation on why we should do this?
