### ISSUE TITLE
If a new subscriber doesn't have a first name, the how-to-slide-into-our-DMs welcome series email shows an empty space.

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1219]
![image.png](https://images.zenhubusercontent.com/5907891d51aa2c30577cf4d5/300dae49-fb35-44fa-8191-842a5409bf41)

**Comment by carogea** [comment]
Would someone mind estimating this at some point? Looks like a good chunk of users don't have names in the system so might make sense to fix if it's easy to

**Comment by ErnieAtLYD** [comment]
Done. As straightforward as going into https://us7.admin.mailchimp.com/campaigns/wizard/autocampaigns?id=1086817 and editing step 3:

```
Hey, *|IF:FNAME|**|FNAME|**|ELSE:|*there*|END:IF|*!
```
