### ISSUE TITLE
Implement Anika's label changes to the newsletter custom fields

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1232]

**Comment by ErnieAtLYD** [comment]
https://pulp-town.wbu.staging.wpengine.com/wp-admin/post.php?post=747&action=edit

**Comment by michaelschofield** [comment]
I'm zoomed out a lot but is this what it's suppose to look like? A lot of the ACF "chrome" is gone from the newsletter? There are no QA notes so I don't know what to expect, but I'm guessing "label changes" don't extend to what I'm seeing. 

![image.png](https://images.zenhubusercontent.com/5907891d51aa2c30577cf4d5/2cd7557b-bff8-46d7-9529-028b1a06e2c0)

**Comment by ErnieAtLYD** [comment]
@michaelschofield no, this is right - the chrome UI isn't the thing to edit, it's verifying that the labels to the form are labeled and reordered correctly w/o the app crashing

**Comment by michaelschofield** [comment]
@ErnieAtLYD Awesome thanks. Firing off a test email and then will deploy
