### ISSUE TITLE
Performance: migrate font loading from FontAwesome CDN to Fontello

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1234]
From [the following blog post on Web Icons and performance](https://www.tomango.co.uk/thinks/improving-wordpress-performance/):
> Icon fonts can be great for serving simple graphical elements to the user without using images. Just like a normal font, icon fonts convert a letter code into a glyph. For most fonts, that glyph represents the original letter, for icon fonts it just so happens that the glyph represents something entirely different. In my case, I use icon fonts for social icons, navigation arrows and a couple of UI elements. These would all be images, or at a minimum one larger image if I didn’t use icon fonts.

> For a long time I turned to FontAwesome for my icon fonts. Then I discovered the awesomeness (that’s a word – right?) that is [Fontello](http://fontello.com/). By only choosing the exact icons that I needed, I was able to create the perfect font for this site. I only needed 8–10 icons for this site so loading in all 519 icons from FontAwesome was completely over the top. By choosing the 10 FontAwesome icons within Fontello, I was able to decrease the size of the font file from 313KB to just 6KB! Pretty nifty, huh?

> The one downside is that the file isn’t being served by a CDN, but I’m happy that the performance boost from a tiny file more than makes up for that.

As our quarterly OKR are to improve performance, I would actually make this (combined with similar tasks) a relatively high priority.

### Definition of done
 - [ ] We are only loading the font based icons we are using, and nothing else.

**Comment by carogea** [comment]
@ErnieAtLYD can you explain a little more + give a priority level?

**Comment by michaelschofield** [comment]
We think that the return on our investment here (for perf) is probably lower than the exponential impact of replacing homepage (etc) components with Vue. Time _might_ be better spent on the latter. Food for thought.
