### ISSUE TITLE
Make clear that members who get membership newsletters have membership status

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1236]
### Job Story
When I'm reading the newsletter and I'm a member (rather than just a subscriber) I want to be able to know that the newsletter I'm reading is the "member" version of the newsletter so I don't have to feel unsure that I'm getting the wrong newsletter.

### Definition of done
 - [ ] It is clear to a WBU member that the newsletter knows they get member content

See conversation here: https://wherebyus.slack.com/archives/CEVTD3EQL/p1556739854009900
Validated multiple times including folks through hello@, current engagement producers and advisors.

**Comment by alexandraleighs** [comment]
Quick note: From my experience, this issue is largely about labeling or signaling that member content is a member benefit so members know that they're seeing something special that's just for them as members and that not all subscribers are seeing the member content.

**Comment by michaelschofield** [comment]
My suggestion is to just use category headers: https://files.slack.com/files-pri/T02A5B3KR-FJJTWGC00/image.png

**Comment by michaelschofield** [comment]
@carogea So these are my suggestions (I recommend doing both). They don't require any new design these are things already in the newsletter template, We're just not using them. I could implement these in just an hour or so.

**Comment by carogea** [comment]
@michaelschofield I'm cool with that. In the future, it would be fun to experiment with more visual design around this, but this is a good start for sure
