### ISSUE TITLE
getsimpleform on corporate site sending blank emails

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1239]
Quality of life issue for Kristem and people w/ access to hello@whereby.us

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_nba5)

Rebekah: We should just use a gravity form

**Comment by michaelschofield** [comment]
A simple addition could be the html5 `required` attribute on the elements we care about.
