### ISSUE TITLE
Promo App: Customer gets error

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1242]
Customer sent the following email:
> Went to pay for the package – thanks for putting that together – and kept getting this error message:

![image](https://user-images.githubusercontent.com/33945/57113522-f17f4700-6d12-11e9-8823-90d1d05f7a91.png)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_nbhp)

**Comment by kassanj** [comment]
So this is a stripe error. I told Schlomo to ask the client to try a different credit card and to make sure all the payment fields are filled out correctly. I have a strong feeling this may be the issue. I haven't changed anything regarding the payment service, plus all our orders have processed fine the pass few months without any errors.
