### ISSUE TITLE
Confirmation code is not matching up for a user

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1246]
<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_nc5x)

**Comment by michaelschofield** [comment]
Generated a new password for this person. Moved to blocked as we await a status update.

**Comment by ErnieAtLYD** [comment]
He's set so we're golden: https://app.frontapp.com/open/msg_2nfm0bx
