### ISSUE TITLE
We should add Transients Manager to our install. Make it easy to clear the occasional cache.

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1249]
## Feature or problem
Describe the feature or problem here: We should add Transients Manager to our install. Make it easy to clear the occasional cache.

### Stakeholders
*Submitted:* michael

### Definition of done
How will we know when this feature is complete?

**Comment by ErnieAtLYD** [comment]
@michaelschofield Frodo? WBA? All plugins?

**Comment by carogea** [comment]
@michaelschofield can you add a DOD and maybe a bit more explanation on why we should do this?
