### ISSUE TITLE
Double underlines for links

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1256]
## Feature or problem
Describe the feature or problem here.

### Reproduction
For the web version of newsletters, links have two underlines under them  instead of one

### Actual behavior
Two lines beneath links

### Suggested expected behavior
A single underline beneath links 

### Suggested priority
priority-medium

### Stakeholders
*Submitted:* ben

**Comment by ErnieAtLYD** [comment]
Closing as dupe of https://github.com/wherebyus/general-tasks/issues/1253
