### ISSUE TITLE
We need to figure out how to get a list of every paid registrant to an event 

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1259]
We need to understand how paid event registration data is stored so we can query the shit out of it.
## DOD

- [ ] A list of every user who has attended a [paid/any] event
- [ ]

### Suggested priority
priority-medium

### Stakeholders
*Submitted:* michael

**Comment by ErnieAtLYD** [comment]
Bruce wants a list of every user that has attended an event.
