### ISSUE TITLE
promotion URLs should not be case sensitive

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1267]
### Reproduction
1. Login as an admin
2. Go to https://promotions.whereby.us/calendar/Pittsburgh - which works fine.
3. Go to https://promotions.whereby.us/calendar/pittsburgh .

### Expected
Should also work fine

### Actual
Error 500

**Comment by michaelschofield** [comment]
@ErnieAtLYD I just learned that case-sensitive URLs is the W3C spec and it's not a fault of rails (or any app), it's by design. Rails routes are deliberately case sensitive because that is the standard.

Anywho, I'll still make it case insensitive for our purposes, just thought it was interesting.
