### ISSUE TITLE
Remove "latest newsletters" on article page

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1280]
### Reproduction steps
1. Go to a page such as https://thenewtropic.com/what-are-your-questions-about-miamis-little-haiti-neighborhood/ on your browser
2. Look at "Latest Newsletters"
3. Nothing is appearing. There's a JS error. JS error is in comments

### DOD
We decided in comments we should just remove this instead of fixing it. So, the DOD is to remove this on the article page.

**Comment by michaelschofield** [comment]
@carogea @ErnieAtLYD In the spirit of reduce to less-is-more as we gradually build new features /d esigns / things for the homepages, what if we just _removed the latest newsletters_ there? The c2a is still there, although maybe we take that away too. 

I'd be interested in stripping down to the barest need of the page until what the page is suppose to do is done really well, reduce the overall complexity of this template, etc. 

I could always fix the latest newsletters, but I doubt we need it. It's one more call ajax call (written with jquery), one more touchpoint. Does its value to the company outweigh the cost of the technical debt?

**Comment by carogea** [comment]
@michaelschofield i would be fine with that. sorry this is coming a week late

**Comment by carogea** [comment]
```
Uncaught TypeError: dateString.getMonth is not a function
    at Object.<anonymous> ((index):352)
    at Function.each (jquery.min.js?ver=3.2.1:2)
    at Object.success ((index):334)
    at i (jquery.min.js?ver=3.2.1:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?ver=3.2.1:2)
    at A (jquery.min.js?ver=3.2.1:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js?ver=3.2.1:4)
```

Viewing the code itself:
```
$.each(data, function(index, newsletter) {
    const dateString = newsletter.datePublishedTimestamp;
            const monthNames = [
              'January',
              'February',
              'March',
              'April',
              'May',
              'June',
              'July',
              'August',
              'September',
              'October',
              'November',
              'December',
            ];
	markup += `
	<li style="list-style: none;">
		<span class="newsletter-date">${monthNames[dateString.getMonth()]} ${dateString.getDay()} &mdash;</span>
		<a href="/newsletter/${newsletter.slug}">
			${newsletter.subject}
		</a>
	</li>
`;
});
```

**Comment by michaelschofield** [comment]
## QA
1. visit this page and confirm that the sign up box is alone without the newsletters on the right
