### ISSUE TITLE
Archive The Incline at archive.theincline.com

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#1292]
Change the domain pointed at spiritedphase1 from https://theincline.com to https://archive.theincline.com

## Feature or problem
Describe the feature or problem here.

### Definition of done
How will we know when this feature is complete?

## UX Check
- [ ] Is there evidence that this is a demonstrable need in WhereByUX?
- [ ] Do insights from such demonstrable need, if it exists, suggest that the thing we want to deliver is a good idea?

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code ()
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing (1)
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check

**Comment by michaelschofield** [comment]
I've added an archive.theincline.com subdomain to cloudflare and wpengine to point at spirited phase 1. Just waiting on wpengine now.

**Comment by michaelschofield** [comment]
`archive.theincline.com` now exists, and we just have to point it at the right spot later.
