### ISSUE TITLE
Redirect old content

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#1293]
-- 1. Map all the urls to theincline.com after a certain date to archive.theincline.com
-- 2. Update wpengine's nginx conf or drop all this in an htaccess somewhere

**Comment by michaelschofield** [comment]
The map will be surprisingly easy. Every article has a date. So given a date, in the *nginx conf or htaccess* we can do

```
#Redirect a sub folder to another site
Redirect 301 /2019/05/31 https://archive.theincline.com/
```
