### ISSUE TITLE
Figure out what it looks like for new Incline site to have old content

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#1297]
broader context:

Pull in an RSS feed / JSON feed into The Incline WBU theme homepage with recent articles from the archive.
----- a. Grapping the JSON / RSS feed from the archive and pulling it in to the homepage (3)
----- b . Figure out what this looks like (and make it look like that). (3)

**Comment by michaelschofield** [comment]
My suggestion :)

https://wherebyus.slack.com/files/UAF4MRKG8/FJBSCC2FL/image.png
