### ISSUE TITLE
Next steps: Tracking signup locations with tags in MailChimp

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1306]
## Feature or problem
Yay, tags in MailChimp! 

 - What signup locations are we now automatically tracking with tags in MailChimp?
 - How should we tag manual imports going forward?
 - Where do the tags appear (MailChimp? WordPress?)
 - Should we audit past data and try to match it to the new tag system? How? 

### Suggested priority
priority-medium

### Stakeholders
*Submitted:* alexandra044

**Comment by ErnieAtLYD** [comment]
Tagging @alexandraleighs for visibility
