### ISSUE TITLE
WP says a membership payment didn't go through

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1312]
## Feature or problem
Describe the feature or problem here.

### Reproduction
I have no idea how this stuff works -- just reporting what I'm seeing on the back end of WP. Looks like it failed for Bob Mason and put his subscription on hold.

### Actual behavior
![image](https://user-images.githubusercontent.com/33945/57659951-26a05a80-7599-11e9-9e81-eaa2919e2856.png)

### Suggested priority
priority-medium

### Stakeholders
*Submitted:* caitlin and Hanaa

**Comment by ErnieAtLYD** [comment]
https://docs.woocommerce.com/document/subscriptions/scheduled-action-errors/
