### ISSUE TITLE
Apply annual membership for all one-time Incline members who have given $96 or more

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#1325]
- Import the expiration date and apply annual membership for all one-time members who have given >= $96. 
- Once their expiration date is up, they would have to pay for another year to continue, or change to monthly.

## How to do this
- [x] Take the NRH export
- [x] Strip out folks who paid 96+ and put it into their own CSV
- [ ] Change expiration date after formatting it for WooCommerce for 1 year from the date of import

**Comment by michaelschofield** [comment]
@carogea https://pittsburgh.wbu.wpengine.com/wp-admin/edit.php?post_type=wc_user_membership&orderby=expiry_date&order=asc so far. Note that some of these members expire as early as June 1, 2019.
