### ISSUE TITLE
In Front App, chats sent from the Promo App should include a source URL and maybe even a location

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1326]
## Feature or problem
Describe the feature or problem here.

### Reproduction
Get pinged a chat from the Promo App

### Actual behavior
I don't know what city the chat is coming from because I don't have metadata about the person

### Suggested expected behavior
I expect to know what city the chat is coming from
This was previously sent from Drift:
![image](https://user-images.githubusercontent.com/33945/57803737-f75f2a00-770d-11e9-9412-e9269083f270.png)

### Suggested priority
priority-medium

### Stakeholders
*Submitted:* ernie

### Definition of done
How will we know when this feature is complete?

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [ ] Brew the coffee

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code ()
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing ()
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check

**Comment by ErnieAtLYD** [comment]
Closing this as it looks like Front does this through some UI:
https://help.frontapp.com/t/80290v/using-front-chat#seewhat-page-your-visitor-is-on . I notified Kateline.
