### ISSUE TITLE
“Account details” should be called “Profile Settings”

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1327]
## Definition of done
- Rename "Account Details" in the membership dashboard to "Profile Settings"

### Why?
Because there are profile _settings_ in there :), not just details. It's also more conventional.

**Comment by michaelschofield** [comment]
## QA
1. Log in to your account
2. Confirm that "Profile settings" shows instead of "Account details"
3. Confirm that all dashboard links work.

**Comment by michaelschofield** [comment]
"Profile settings" template still says "Account Details"
