### ISSUE TITLE
Browser template images appear to be broken after switch from get_field to get_post_meta.

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1356]
## Feature or problem
Describe the feature or problem here.

### Reproduction
Take a look at newsletters in the browser. If you inspect the image src, you'll see that in some cases it's _a number_ - not a url. 

My guess is that this is the return of `get_post_meta` on photo/image types of ACF fields, which we might not have QA'd appropriately. Haven't confirmed though.

### Suggested expected behavior
All content in browser newsletter looks normal.

### Suggested priority
priority-high

### Stakeholders
*Submitted:* michael

### Definition of done
How will we know when this feature is complete?

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [ ] Brew the coffee

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code ()
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing ()
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check

**Comment by michaelschofield** [comment]
Heya @ErnieAtLYD. I released newsletters but didn't remember that we'd done some refactoring with get_field => get_post_meta. My guess is that `get_post_meta` on a image-type ACF field only returns an ID instead of a url. The newsletter template looks normal, and those are still get_fields. I haven't confirmed it beyond that.

My gut says that the get_post_meta refactoring should be swithced abck to the get_fields, and then a eparate refactoring ticket made to change that back so we can remember to track it.

-- edit

Yep you can see on https://thenewtropic-com.wbu.staging.wpengine.com/newsletter/2019-02-12-this-is-a-test-newsletter-for-ismember-merge-tags/ this error

>  Warning: Illegal string offset 'ID' in /nas/content/staging/wbu/wp-content/plugins/wbu-newsletters/includes/email-templates/parts/section_1.php on line 6

**Comment by michaelschofield** [comment]
@carogea FYI I moved this into this sprint because, oops, our bad.

**Comment by ErnieAtLYD** [comment]
Oops. https://support.advancedcustomfields.com/forums/topic/get_post_meta-doesnt-work-with-images/

This has been difficult to test because on my development build, I'm not able to upload images into the newsletter. Not sure why but whenever I tried to debug it just caused a rabbit hole to go down so I avoided it.

What I'll do in the meantime is get a copy of the production DB and get it on my local to replicate the issue, then go from there.

**Comment by michaelschofield** [comment]
## QA from the PR

Confirm that for legacy newsletters, the images appear as expected when going to /newsletter

Confirm that when you create new newsletters that the images appear in the email template

Confirm that when you create new newsletters that the images appear as expected when going to /newsletter

**Comment by michaelschofield** [comment]
@ErnieAtLYD Fyi the ACF refactor PR choked on a php syntax error https://app.codeship.com/projects/252823/builds/41905124?pipeline=04645d2b-9da4-4e11-a9fc-ecf31cccb23d 

I rolled it out of staging so if you want to push to the same issue go for it. Honeslty I'm surprised codeship didn't crack on the issue branch O_o. But anyway you can see there's an unexpected end of file when expecting an if/endif.

**Comment by ErnieAtLYD** [comment]
oooh fun, and on top of it it _also_ sneaked past unit tests. Hooray for CI/CD, I guess?
