### ISSUE TITLE
In posts, our editor suggests only an `h4` - we should undo this. The editor should introduce h2s and h3s.

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1376]
## Feature or problem
When you create a new post, it lets you make a H4, but it should not do this. This is bad for accessibility, among other things (SEO etc). 

### Stakeholders
*Submitted:* michael

### Definition of done
How will we know when this feature is complete?

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [ ] Brew the coffee

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code ()
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing ()
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.
1. Create a new post or page
2. Confirm that you can only choose from Paragraphs, Headings, and Subheadings.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check

**Comment by michaelschofield** [comment]
Our page styles are a bit weird.

![image.png](https://images.zenhubusercontent.com/5907891d51aa2c30577cf4d5/011cbe42-a147-4ce9-b6ab-4344d0c551f3)

In an ewsletter this looks fine
https://wherebyus.slack.com/files/UAF4MRKG8/FKBFNM96U/image.png

**Comment by ErnieAtLYD** [comment]
Related: https://github.com/wherebyus/whereby.design/pull/203
