### ISSUE TITLE
Setup the Incline with a Facebook Pixel

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1384]
## Feature or problem
Describe the feature or problem here.

### Reproduction
^

### Suggested priority
priority-medium

### Stakeholders
*Submitted:* michael

### Definition of done
How will we know when this feature is complete?

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [x] Send pixel to Schofield

**Comment by ErnieAtLYD** [comment]
Sent Pixel ID to Schofield, but not sharing here because technically this is a public repo.
