### ISSUE TITLE
Update Bridgeliner & Pulptown's Creative studio gravatar on Wordpress to brand logo (also The Incline if not already done)

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1408]
## Feature or problem
Update Bridgeliner & Pulptown's Creative studio gravatar on Wordpress to brand logo (also The Incline if not already done)

Current tasks
 - [x] Start thread in slack on what the email addresses for all creative studios should be
 - [x] If the emails need to be on subdomains, create those tasks in Google Admin
 - [ ] Attach avatars to all emails
 - [ ] Create a page in library talking about all of this

### Reproduction
No steps, just that the logo/avatar for our creative studio on our WordPress sites needs to be updated to the logo. I can't seem to change it. 

Avatars for our creative studio accounts in word press have logos when posting stories, not a generic avatar. 

### Suggested priority
priority-low

### Stakeholders
*Submitted:* brucepinchbeck

### Definition of done
How will we know when this feature is complete?

**Comment by ErnieAtLYD** [comment]
Welp, this opens up a can of worms. Started a thread at #creative-all for their thoughts about what email addresses they should use, much less what logos should be attached with their accounts.

**Comment by ErnieAtLYD** [comment]
i’ve set up `studio@[domain]` to forward to Bruce and I but i can’t get it to work. i’m blocked until it does.
