### ISSUE TITLE
How to trigger Incline member welcome email

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1425]
## Feature or problem
I think the Incline member welcome email needs a different trigger.

The trigger for other brands is when a contact's ‘ismember’ merge tag changes to ‘1’ (and they're active).

‘ismember’ merge tag is already ‘1’ from Incline's hub import of members, so if people join through our site and give us their cc info, *how do we trigger the member welcome email?*

### Actual behavior
Member welcome email hasn't sent to ~10 members who have joined through our site in past week

### Suggested expected behavior
Send member welcome email from MailChimp to Incline members who join  program through our site

### Suggested priority
priority-medium

### Stakeholders
*Submitted:* alexandra044

### Definition of done
How will we know when this feature is complete?

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [ ] Brew the coffee

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code ()
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing ()
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check

**Comment by carogea** [comment]
@michaelschofield i'm wondering if we should have a different system for doing these welcome emails for incline members who sign up for membership through WC? feels like it's an edge case we're only going to have to deal with this month, but i also think it's important to figure it out since we want to retain these members + give them a good impression of the new membership program

**Comment by carogea** [comment]
@michaelschofield like could we have them do it manually through mailchimp and keep track of the members who switch over
