### ISSUE TITLE
HMW track when members receive swag

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1430]
## Feature or problem
We'll lose our current system for tracking that members have received swag when we move to eventbrite, so we'll need a new solution for this. It's on Bruce's radar, but want to capture it with all of prod/tech, too. 

### Suggested expected behavior
We have a way, even if it's still manual, to track which members have received swag so we don't give it out to members  more than once. 

### Suggested priority
priority-medium

### Stakeholders
*Submitted:* alexandra044

**Comment by alexandraleighs** [comment]
rsm just reminded me that we can still check the swag box in member profiles in wordpress so this isn’t too big of a deal. but it would be awesome if we could integrate it with eventbrite if that’s where we’ll be checking in attendees so we can do both steps at the same time in the same place.

**Comment by michaelschofield** [comment]
We're closing this ticket because technically a solution already exists.
