### ISSUE TITLE
NPS email name field

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1440]
## Feature or problem
Describe the feature or problem here.

### Reproduction
Ask Nicely used my last name in the subject line and greeting instead of my first name

### Actual behavior
"Hi DeJarnette"

### Suggested expected behavior
"Hi Ben"

### Suggested priority
priority-low

### Stakeholders
*Submitted:* ben

**Comment by ErnieAtLYD** [comment]
turns out that particular account had your name as `DeJarnette null`. That’s a manual thing that has to be done as a case by case basis, and i fixed it for this specific case.
