### ISSUE TITLE
Tag subscribers from FB lead gen ads in MailChimp

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1467]
## Feature or problem
Describe the feature or problem here.

### Reproduction
The tag should be social_lead_gen

I looked in MailChimp and none of the subscribers from social lead gen ads this month have been tagged. BL and PT have had active ads running and new subscribers added from social. 

I couldn't find an existing ticket for this in Zenhub. I think this tagging is setup in Zapier.

### Actual behavior
subscribers aren't  being tagged 

### Suggested expected behavior
Subscribers who signup through a lead gen ad should be tagged with the MailChimp tag social_lead_gen

### Suggested priority
priority-medium

### Stakeholders
*Submitted:* alexandra044

### Definition of done
How will we know when this feature is complete?

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [ ] Brew the coffee

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code ()
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing ()
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check

**Comment by alexandraleighs** [comment]
Hi @carogea Curious when this will get picked up from the backlog? It's the last signup location source to need tags and I'm hoping to get a new Grow dashboard created with this info once all of the tags are setup.
