### ISSUE TITLE
When I see a newsletter conversion box on the website, it says "checkout" instead of "check out"

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1512]
## Feature or problem
In the automated newsletter conversion box, "Checkout our latest newsletter" should be "Check out our latest newsletter."

## UX Validation
Validated

### Suggested priority
Medium

### Stakeholders
*Submitted:* ben

### Definition of done
How will we know when this feature is complete?

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [ ] Brew the coffee

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code ()
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing ()
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check

**Comment by carogea** [comment]
@michaelschofield do you think this is a 1 pointer

**Comment by michaelschofield** [comment]
@carogea I'd actually give it _two_ because there are two moving parts. We have to

1. Update the component in the design system
2. Update Frodo and rebuild it with the latest design system
