### ISSUE TITLE
When someone tries to buy a membership with the Promo code VIPMember, they get an error message

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1514]
## Feature or problem
The error message is: "Sorry, this coupon is not applicable to selected products"

## UX Validation
Validated

### Suggested priority
High

### Stakeholders
*Submitted:* ben

### Definition of done
How will we know when this feature is complete?

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [ ] Brew the coffee

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code ()
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing ()
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check

**Comment by carogea** [comment]
@michaelschofield Do you know how often this occurs?

**Comment by michaelschofield** [comment]
@carogea I think this was more of a coupon thing rather than a _bug_. I didn't follow the thread on slack but @alexandraleighs can maybe confirm that this isn't a bug.
