### ISSUE TITLE
Verify theincline.com with FB 

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1716]

**Comment by alexandraleighs** [comment]
Hi, Just tried to verify this and got an error msg from FB that reads "DNS TXT Record Mismatch
We did not find a matching DNS TXT entry on your domain." 

Please let me know how I can help. Here are the instructions from FB:

Add a DNS TXT record to your domain host to prove that you own the domain. Most domain hosts allow this, but the specific steps for each service will vary. If you need help, please contact your domain host's support team or check their documentation.

DNS TXT Record

Here are the basic steps:

- Login to your domain registrar and visit the DNS records section.
- Add this TXT record in your DNS configuration:
- facebook-domain-verification=fwr0h6106n2l1bswz2surmlx2w1b4x
- Add @ in the Host field (if your domain host requires it)
- Wait until your DNS configuration changes have spread across your website's domain servers (this may take up to 72 hours), then click Verify.

**Comment by alexandraleighs** [comment]
Just checked this again, and I was able to verify. Thanks for your help!
