### ISSUE TITLE
Investigate whether we use the "Leaderboard" section in the newsletters. If not, delete it.

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#694]
## Reproduction Steps
We include a leaderboard content section in the newsletter but if I recall it's not being used. We should remove it to reduce tech debt.

### Additional information:
 - BTID-358
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recxjefG53YkgSCe9) - (may include image attachments)

### Submitted by
Name: Michael Schofield 
Email: michael@whereby.us
Slack ID: michael

**Comment by kassanj** [comment]
I checked on production and there is no "Leaderboard" section that currently exists on newsletter the newsletter builder.
