### ISSUE TITLE
Remove the "referrals" My Account page and menu link

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#726]
## Reproduction Steps
Right now in your account dashboard you can view a "Referrals" page accessible via the menu. This is pretty much an exact clone of the referrals information we show right in your dashboard. 

For now, since it's not showing anything extra or adding additional value, we should remove it.

## Expected Results
When visting MyAccount, there shouldn't be a "Referrals" menu option. Additionally, /my-account/referrals links need to be updated if they're present anywhere, and a high-level redirect probably put in place.

### Additional information:
 - BTID-365
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recCZoCNSemu1a2R4) - (may include image attachments)

### Submitted by
Name: Michael Schofield 
Email: michael@whereby.us
Slack ID: michael

**Comment by michaelschofield** [comment]
Looks good. Ready to go \m/
