### ISSUE TITLE
why is a dude's subscription on-hold but his membership is active?

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#747]
## DOD
What should the ideal case be? Is this a bug?  Ask Briana for clarification?

## Reproduction Steps
stuarttkennedy@gmail.com emailed hello@ because Briana sent a "hey you were an annual member just a heads up that if you want to renew, you'll get an email 3 days before your expiration date to renew you to our new monthly program" mass email. 

We noticed that his subscription was "on hold" but his membership status was "active" - he would not have been charged bc his subscription was on hold .. Q here is has this happened to anyone else? Also Q is does this mean he has been seeing member content even though he hasn't been paying for it?

### Additional information:
 - BTID-375
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recyRaGCz6HpnaUOq) - (may include image attachments)
- As of 2/26 this has not been addressed, and it should only be affecting about 20-30 users.

### Submitted by
Name: Briana Brown 
Email: briana@whereby.us
Slack ID: briana

**Comment by ErnieAtLYD** [comment]
Briana: what is the question you're trying to answer here?
