### ISSUE TITLE
Two book club events show up for Bridgeliner, even though they're the same URL

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#757]
## Reproduction Steps
1. Go to https://bridgeliner.com/
2. Look at "Upcoming Events"

## Expected Results
There is possibly one event

## Actual Results
There are two events.

EXTRA CREDIT: if a city only has one event do we really want to have that on its own row? If not how should it look instead?

### Additional information:
 - BTID-379
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recTo3qlZ8EOWlt1W) - (may include image attachments)

### Submitted by
Name: Ernie Hsiung 
Email: ernie@whereby.us
Slack ID: ernie

**Comment by carogea** [comment]
unclear if this is still an issue
