### ISSUE TITLE
gifs incorrectly sized in newsletters

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#802]
## Reproduction Steps
Opened today’s PT and TNT to see that the gifs were too smal

## Expected Results
Gifs fill the nl container

## Actual Results
Too small

### Additional information:
 - BTID-406
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/rec5Gh9GwpgF8JgG5) - (may include image attachments)

### Submitted by
Name: Rebekah Monson 
Email: rebekah@whereby.us
Slack ID: rebekah

**Comment by kassanj** [comment]
Checked the old newsletters (Feb 15, Feb 14, Feb 13) for Pulptown and The New Tropic on iPhone 8 plus and Gmail. The GIFs look fine to me.
