### ISSUE TITLE
Refactor-out all replace_merge_tags instances in wbu-newsletters for the corresponding method in WhereByApp

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#817]
## Problem
We need to start refactoring `wbu-newsletters` if we ever want to build further features on it with confidence. We can start by abstracting the nascent NewsletterService from WhereByApp into its own private repository, then loading it both in WhereByApp and wbu-newsletters via composer.

Then, bit by bit, we can target things we want to destroy. 

We'll start with `replace_merge_tags()` method in WBU Newsletters.

- [x] Abstract NewsletterService/Repo/Models/DTOs into its own private repository
- [x] Load NewsletterService with composer in wbu-newsletters and WhereByApp
- [x] Replace all instances of `replace_merge_tags` use with the corresponding NewsletterService method (`replaceMergeTags()`, I think)
- [x] Delete the `replace_merge_tags()` method entirely and its unit tests.

## Expected Results
1. Everything should load normally and without error
2. Make a note of then confirm that wherever replace_merge_tags is being used in wbu-newsletters, it's works as expected.

**Comment by kassanj** [comment]
There are a lot of things going on in this ticket. 

So first, I create a new repo called NewsletterService.  I added all the existing Newsletter code from `wherebyapp` into the NewsletterService repo. `wherebyapp` has access via `composer.json`. 

Then, I removed `replace_merge_tags` function from `wbu-newsletters` and loaded `NewsletterService` repo via `composer.json`.

NewsletterService repo -> https://github.com/wherebyus/NewsletterService
wbu-newsletters -> https://github.com/wherebyus/wbu-newsletters/pull/550
wherebyapp -> https://github.com/wherebyus/wherebyapp/pull/506
