### ISSUE TITLE
Refactor: use event emission to lean-down ReferralController

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#828]
## Problem
Many of our ReferralController methods are too procedural in that they rely on event A to happen before event B can happen, and so on. In certain cases, these events don't really have anything to do with each other - other than the fact we want to use event A as a "trigger."

The opportunity here is to emit an event when Event A happens at the right spot, then have other methods listen for it that need it.

In WordPress/WhereByApp, the obvious route is to create custom actions and then listen for those actions in the provider. 

An example of this is already being done in `updateUserMeta` in the MemberRepository. 

Using event emission and listening, we should be able to significantly lean down ReferralController.

## Expected Results
No ReferralController method should have more than 2 `if` conditions. Ideally, controller methods should have none. 

## QA
1. Follow an invitation link and sign up with a new email. The referrer should get credit, the new email should be subscribed, a new user with that email should be created. No errors.
2. Create, delete, edit Referrals, view the leaderboard, etc. No errors.
3. Referral progress-bar should reflect reality in `my-account`

**Comment by michaelschofield** [comment]
Looks and performs great!
