### ISSUE TITLE
Fix Outlook image issues for redesign

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#830]
Images are loading well throughout except in Outlook 2019 (Win 10) 
<img width="529" alt="screen shot 2019-03-08 at 10 38 01 am" src="https://user-images.githubusercontent.com/47572599/54038502-b4715b00-418e-11e9-939d-6b93c4d071f9.png">

DOD: Images load full-width with no padding in Outlook

**Comment by kassanj** [comment]
[Uploading... Screen Shot 2019-03-08 at 11.13.44 AM.png ]
