### ISSUE TITLE
Email capture form on bridgeliner.com not working or sending confirmation email

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#846]
DOD: Figure out what happened!

## Reproduction Steps
input email for subscription on bridgeliner.com No confirmation and no on page notification

## Expected Results
to get subscribed 

## Actual Results
not subscribed

### Additional information:
 - BTID-426
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recRGjuRVtFhy0xxX) - (may include image attachments)

### Submitted by
Name: Schlomo Rabinowitz 
Email: schlomo@whereby.us
Slack ID: schlomo

**Comment by kassanj** [comment]
I just tried signing up via `bridgeliner.com` on my mac air chrome browser and it worked for me.
The screen displayed confirmation text `Thank you for subscribing` and I received a welcome email.

**Comment by michaelschofield** [comment]
I followed the same steps as @kassanj and it works for me too.
