### ISSUE TITLE
table border visible in title sponsor block in newsletter redesign

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#858]
## Reproduction Steps
look at one of the redesigned test emails. a small gray border is visible between the image and the text

## Expected Results
there should be no visible border

## Actual Results
![image](https://user-images.githubusercontent.com/33945/53386625-d15c9180-3937-11e9-817e-d808a7d7da13.png)

![image](https://user-images.githubusercontent.com/33945/53386637-d91c3600-3937-11e9-9d37-ad9614e2df12.png)

### Additional information:
 - BTID-430
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recHzUnPUPkzVGaVl) - (may include image attachments)

### Submitted by
Name: Rebekah Monson 
Email: rebekah@whereby.us
Slack ID: rebekah

**Comment by carogea** [comment]
@michaelschofield @kassanj looks like there is still an issue here with outlook 2019 (win 10) ![Screen Shot 2019-03-05 at 1.27.45 PM.png](https://images.zenhubusercontent.com/5c630d90c95c1c66f2b87ae3/e6b55920-c731-46e9-874b-ad0cd0cffa34)
