### ISSUE TITLE
Low-severity security vulnerability in Lodash on Frodo. We need to update that and then ensure any Vue app using Lodash QAs.

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#864]
## Reproduction Steps
^

### Additional information:
 - BTID-431
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/rectrASvEmTGJZM1b) - (may include image attachments)

### Submitted by
Name: Michael Schofield 
Email: michael@whereby.us
Slack ID: michael

**Comment by ErnieAtLYD** [comment]
https://github.com/wherebyus/frodo/commit/bda947a9560697610ec1270c6d4ad4526ebf4a17
