### ISSUE TITLE
Broken image in double opt-in email 

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#873]
## Reproduction Steps
See screenshot below -- there's a broken image in the campaign. I would fix it myself, but I can't find where that campaign lives in MailChimp or WordPress

## Actual Results
![image](https://user-images.githubusercontent.com/33945/53748351-0c8c2280-3e5a-11e9-9917-5b375d067d48.png)

### Additional information:
 - BTID-434
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recRilMvGdJuLfkU9) - (may include image attachments)

### Submitted by
Name: 
Email: 
Slack ID:

**Comment by carogea** [comment]
I just replicated this by subscribing to Pulptown and Bridgeliner on another one of my email addresses and it appears to be fixed
