### ISSUE TITLE
Mobile membership page, login module wonkiness

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#877]
## Reproduction Steps
See screenshot -- things look pretty funky on mobile ios, iphone 7, safari

## Actual Results

![image.png](https://images.zenhubusercontent.com/5b3b8639fc589b1d091c443c/4c83b464-0e62-465e-8711-d29d6ca2de09)

### Additional information:
 - BTID-438
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recfttX4GnYadpthW) - (may include image attachments)

### Submitted by
Name: 
Email: 
Slack ID:

**Comment by ErnieAtLYD** [comment]
I plan on giving the login component a CSS `min-width` of 320px.

**Comment by ErnieAtLYD** [comment]
![image](https://user-images.githubusercontent.com/33945/54218421-ee5e9c00-44c3-11e9-8032-1c977e059941.png)

Minimum login width you come to the above

**Comment by michaelschofield** [comment]
## QA
1. On a small screen or squished browser, confirm that the line-height is appropriate for the heading
2. Confirm that buttons don't leak off the edge of the component and format in a stack, then on larger screens format side by side
3. Confirm that when the loading icon in the button appears, the button label remains centered.
