### ISSUE TITLE
What do we do in the case if the credit card fails? Do we send an email at all?

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#883]
Ben reported this. Can you follow up with him? What should be the right behavior?

ANSWER: They should be sent an email instructing them how to update their credit cards.

DOD: Figure out the right behavior, and then make note of that in the Membership doc that Briana wrote previous.

**Comment by carogea** [comment]
The "right" behavior should be that an email is sent to them, with instructions on how to change their credit card info. I am making a ticket for this.

**Comment by carogea** [comment]
https://app.zenhub.com/workspaces/tech-team-repos-5b3b863cf36bf13b2ad5b66e/issues/wherebyus/general-tasks/907
