### ISSUE TITLE
Create an API that produces events to be automated

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#885]
DOD: design a RESTful API that retrieves 
 * the name and link to the next event in a city that is hosted by us

CONSTRAINTS
* Event: Only fetch events hosted by us. If there are no upcoming events hosted by us, don't fetch any content

**Comment by michaelschofield** [comment]
Hey fam. I'd even go so far that these bullets themselves are two separate tickets. One is a *guides API* and the other is an *events API*.

**Comment by carogea** [comment]
@michaelschofield Done: this is now the events one, and content one is here https://github.com/wherebyus/general-tasks/issues/919

**Comment by kassanj** [comment]
When digging into the tribe_events postmeta, `_EventOrganizerID` is the only way to retrieve a list of events by a specific organizer. Each child site would need to set it's own ID (TNT, TE, PT, BL), which is not ideal.

**Comment by kassanj** [comment]
### QA Notes
1. Visit http://miami.wbudevelop.wpengine.com/wp-json/whereby/api/upcoming-event
2. Expect: The page to render an array object, which should include a title, slug and startDate values.
