### ISSUE TITLE
Automate event + recent content in renewal email

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#896]
PARAMETERS
* Event: Soonest upcoming Wherebyus hosted event in the newsletter's city. Text will read "Free or discounted admission to all of (newsletter name)'s events, like (event name)."
* If there is no upcoming event, text will read "Free or discounted admission to all of (newsletter name)'s events."
* Content: Most recent guide page. Text will read "Supporting community-centric storytelling in (city name), like (story name)."

DOD: When renewal email is sent to remind members that their membership will renew soon, an upcoming event and the most recent guide page auto-populates. If there is no upcoming event hosted by Wherebyus in that city, text will read "Free or discounted admission to all of (newsletter name)'s events."

**Comment by carogea** [comment]
![Screen Shot 2019-02-27 at 9.26.40 AM.png](https://images.zenhubusercontent.com/5c630d90c95c1c66f2b87ae3/c9e845c1-1dc2-40d5-a1f5-35afa454361e)

**Comment by carogea** [comment]
Check: How much does Alexandra want this now, with changes to what she's working on?

**Comment by alexandraleighs** [comment]
yes

**Comment by michaelschofield** [comment]
Moving this bad boy back into the backlog after @alexandraleighs's confirmation.
