### ISSUE TITLE
Random Checkbox on PDX Membership Page

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#897]
## Reproduction Steps
Go to https://bridgeliner.com/membership/.

There's a random checkbox at the bottom of the membership landing page that says "Create an Account?" But it doesn't do anything when you click it. It's just confusing and redundant. 

Also, there's some language at the top of this membership page that really needs to be tightened up. Can someone point me to the place in WordPress where I can make those changes?

## Expected Results
See description above

## Actual Results
See screenshot
![image](https://user-images.githubusercontent.com/33945/53896870-ed7cc480-4002-11e9-9ba3-bd1435ab9e3f.png)

### Additional information:
 - BTID-443
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recz3WUxgiQnCOmMd) - (may include image attachments)

### Submitted by
Name: 
Email: 
Slack ID:

**Comment by ErnieAtLYD** [comment]
Ugh. Good catch. This had to be unchecked:
![image](https://user-images.githubusercontent.com/33945/53898163-8c0a2500-4005-11e9-8009-459b841e00a8.png)

**Comment by ErnieAtLYD** [comment]
Ben, as far as editing the copy you can edit the Membership page at https://bridgeliner.com/wp-admin/post.php?post=9499&action=edit and then edit the attribute inside the shortcode with the copy you need.
