### ISSUE TITLE
Automate event + most recent content in welcome email

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#905]
PARAMETERS
* Event: Soonest upcoming Wherebyus hosted event in the newsletter's city. Text will read "Your membership gets you free or discounted admission to all of (newsletter name)'s events, like (event name)."
* If there is no upcoming event, text will read "Your membership gets you free or discounted admission to all of (newsletter name)'s events."
* Content: Most recent guide page. Text will read "Your membership supports community-centric storytelling in (city name), like (story name)."

NOTE
We want to investigate sending this email through WordPress instead of through MailChimp, which will make this significantly easier to build.

DOD: When welcome email is sent to new members, an upcoming event and the most recent guide page auto-populates. If there is no upcoming event hosted by Wherebyus in that city, text will read "Your membership gets you free or discounted admission to all of (newsletter name)'s events."

**Comment by carogea** [comment]
![Screen Shot 2019-02-27 at 9.24.54 AM.png](https://images.zenhubusercontent.com/5c630d90c95c1c66f2b87ae3/c883c19c-71d6-4db7-aa5a-f171a4995b08)
Sample welcome email

**Comment by carogea** [comment]
@alexandraleighs is this still something you care about doing?

**Comment by alexandraleighs** [comment]
yes
