### ISSUE TITLE
Localize PDX order/renewal failure email follow-ups for other cities

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#907]
Ernie has set up two Follow-up settings in Bridgeliner:
 - A [renewal failed follow-up](https://bridgeliner.com/wp-admin/post.php?post=69614&action=edit)
 - An [order failed follow-up](https://bridgeliner.com/wp-admin/post.php?post=69615&action=edit)

This has been completed for PDX, but this needs to be localized for MCO, MIA and SEA. You'll just need to create new Follow-up post types for each city and then localize the information as appropriate. You'll also want to make sure that for the Order Failed Follow-up, **the Import Existing Orders checkbox is checked** so emails can be set for people who's credit card has failed but were never notified.

## DOD
- [x] Follow-ups created for MIA
- [x] Follow-ups created for MCO
- [x] Follow-ups created for SEA

**Comment by carogea** [comment]
Briana/Alexandra will get copy probably on Thursday

**Comment by michaelschofield** [comment]
@carogea sez
> Briana and Alexandra said they would get copy for this email, i'll ping them in a bit and see where that's at

**Comment by carogea** [comment]
email copy @michaelschofield 

Hi [member name],

Hope things are good! We wanted to let you know that your most recent membership renewal order couldn't be completed with the card on file. 

If you'd like to re-activate your membership, you can update your card info in the "Payment methods" section of your account page and that should renew your membership automatically. If it doesn't (i.e. you don’t see member perks in your daily [brand] newsletter), then just shoot us a note and we'll help you out. 

Reply with any questions, and thanks again for your support!

[ld name]
Director, [brand]

https://docs.google.com/document/d/11k5JdWO534ODzA9TzFo_NyJ0yvkpCnoxN5r6uweBld0/edit?usp=sharing

**Comment by carogea** [comment]
Kristem can do
