### ISSUE TITLE
In Memberships view of WooCommerce, not all member statuses appear

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#909]
## Reproduction Steps
I’m looking at ‘cancelled’ status members in wordpress under Memberships, and I notice that while as of Friday each site had a few (3-5) cancelled members so far this year, now there’s 0-1 members showing as cancelled for each brand. 
Do you think the syncing process could turn “cancelled” status members to “active” status members somehow? 
Could this be a bug?
Or a WooCommerce change?
You can still see cancelled and pending cancellation members under the Subscriptions view, but I don't see a way to export this data so counting totals by status will be hard. I used to use the Memberships view and export function to do this.

More convo:
https://wherebyus.slack.com/archives/CEVTD3EQL/p1551886636019300

### Additional information:
 - BTID-448
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recZRPz04N51pdtUL) - (may include image attachments)

### Submitted by
Name: 
Email: 
Slack ID:

**Comment by ErnieAtLYD** [comment]
Human error.
