### ISSUE TITLE
Update copy on Product/Checkout pages for all brands

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#912]
![image.png](https://images.zenhubusercontent.com/5b3b8639fc589b1d091c443c/eca46f34-633c-4cb6-bbca-02c242c65160)

Content is currently in a short tag. An additional attributes would need to be created to handle pre-content and post-content.

The top part of the card is WP and the bottom is viewapp. Moving them around will be tricky and have some strange side effects. note: We can't get in the habit of making these changes without good evidence.

**Comment by carogea** [comment]
@michaelschofield says no !!

**Comment by ErnieAtLYD** [comment]
From Alexandra: "if we can’t move it that’s all I need to know. I can shorten the copy. i think it’s imp. to try to have the price options show without having to scroll"
