### ISSUE TITLE
Update copy of SITE membership order confirmation

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#913]
### Current copy
Thank you. Your order has been received.

### New copy
You’re in! We're emailing you an order confirmation with more information.

### For if/when we can personalize to membership
You’re in! We’ll email you an order confirmation, and start delivering your member perks in your daily [brand] newsletter.

### DOD
 Site membership order confirmation is updated with above text

**Comment by ErnieAtLYD** [comment]
```
// Removes Memberships "thank you" message from thank you page
function sv_wc_memberships_remove_email_thankyou() {
	if ( function_exists( 'wc_memberships' ) ) {
		remove_action( 'woocommerce_thankyou', array( wc_memberships()->get_frontend_instance(), 'maybe_render_thank_you_content' ), 9 );
	}
}
add_action( 'init', 'sv_wc_memberships_remove_email_thankyou' );
```

**Comment by ErnieAtLYD** [comment]
![image.png](https://images.zenhubusercontent.com/5b3b8639fc589b1d091c443c/75e3b9b7-e7d7-4661-93b4-67e130a25d68)

**Comment by michaelschofield** [comment]
@carogea Hmm. So I might recommend this ticket to be closed. I don't think it meets some basic [new] backlog requirements anymore:

1. There's no demonstrable proof that anyone has ever had an issue with the copy. So it's not a user-motivated change.
2. Changing the copy, being WooCommerce, is *messy* and has side effects (e.g., you would need to make this change only on membership orders, but event orders, or other orders).

Given the lack of demonstrable _need_ and the ugh-ness of making the change, I think it disqualifies itself.
