### ISSUE TITLE
Membership article on BL home page

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#916]
## Reproduction Steps
Go to bridgeliner.com > you'll see our membership landing page listed among our latest articles. That shouldn't be the case. See screenshot. At the very least, that page should have a title and an image if it's going to show up there

### Additional information:
 - BTID-451
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recybvqJ80ZvuWXyw) - (may include image attachments)

### Submitted by
Name: 
Email: 
Slack ID:

**Comment by ErnieAtLYD** [comment]
this should be fixed now. Basically it was because Schofield had to create a new blog post and it was one of the last 3 posts published. I just changed the publish date.
