### ISSUE TITLE
Fix promo padding

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#917]
Padding between lines in the promo ad is consistently very tight. 

More info and screenshots here: https://wherebyus.slack.com/archives/C63BGU20N/p155198341513820

DOD: Padding more consistently matches the rest of the NL, and mockup on wherebydesign (example in comment)

**Comment by carogea** [comment]
wherebydesign mockups![Screen Shot 2019-03-07 at 1.52.15 PM.png](https://images.zenhubusercontent.com/5c630d90c95c1c66f2b87ae3/20d8362d-924d-49d7-acea-20659d9bfd7d)
[Uploading... Screen Shot 2019-03-07 at 1.52.08 PM.png ]

**Comment by ErnieAtLYD** [comment]
Replicate of wherebyus/frodo#802
