### ISSUE TITLE
Remove preview text from newsletter interface/header

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#918]
Preview text functions to show readers a preview in their email clients. 

![Screen Shot 2019-03-07 at 2.26.14 PM.png](https://images.zenhubusercontent.com/5c630d90c95c1c66f2b87ae3/fd7e4b2e-c87f-4df7-a4d7-49567ec0b6a0)

We should remove it from the newsletter header interface

![Screen Shot 2019-03-07 at 2.38.02 PM.png](https://images.zenhubusercontent.com/5c630d90c95c1c66f2b87ae3/23dd97b2-1c79-4b4b-b417-7f8c7adf426c)

DOD: Newsletter preview text doesn't appear in the header, but still appears as preview text in the inbox. The other header text is reformatted to be fewer lines and fit the space.

**Comment by michaelschofield** [comment]
## QA
1. Send a test email to yourself and confirm in whatever client you have that preview text, whatever you added from the builder, shows as such. 
2. Open the email and confirm the preview text is gone.
3. Confirm that "View Online" is on the upper right and "Add us to your safelist" is on the upper left.
4. Confirm that both links work.
5. Sned a test email to litmus and make sure nothing looks jacked.
