### ISSUE TITLE
Create an API that retrieves content to be automated

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#919]
DOD: design a RESTful API that retrieves 
 * the name and link to the most recent guide page published on a city's site

CONSTRAINTS
* Content: Only fetch most recent guide page.

**Comment by kassanj** [comment]
There are 2 pull requests for this ticket

WhereByApp -> https://github.com/wherebyus/wherebyapp/pull/522
NewsletterService -> https://github.com/wherebyus/newsletterservice/pull/2/

**Comment by kassanj** [comment]
### QA Notes
1. Visit http://miami.wbudevelop.wpengine.com/wp-json/whereby/api/latest-guide-post
2. Expect: The page to render an array object, which should include a slug and title.
