### ISSUE TITLE
Classic newsletter template formatting was broken this morning (8 Mar 2019)

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#922]
## Reproduction Steps
Look at today's newsletters in gmail (desktop). They don't have any formatting.

### Additional information:
 - BTID-454
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recyVxOyLF5S7doaL) - (may include image attachments)

### Submitted by
Name: 
Email: 
Slack ID: ben

**Comment by ErnieAtLYD** [comment]
https://litmus.com/builder/1f1434d - I see CSS references to `classicEmailWrapper` but the `classicEmailWrapper` CSS is included in the `raw-newsletter-template.php` in the `*|IF:ISMEMBER|*` block.

I would touch it but I don’t know how you generate raw-newsletter-template.php.
