### ISSUE TITLE
Outro block in redesign has lots of spacing

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#923]
Looks like there is a lot of spacing below and above the text in the outro block. Check to see if there is an extra, empty `<p></p>`

From Michael: "So what's happening here is basically that is content is in a `<p>` tag. The block itself is correctly sized, but paragraphs add a little extra margin at the bottom, so when there's new stuff. There might literally be an extra and empty `<p></p>` underneath " - The New Tropic"."

DOD: If there is an extra <p></p> remove it; if there is not, mark it as closed 

![gmail chrome.png](https://images.zenhubusercontent.com/5c630d90c95c1c66f2b87ae3/c65ba627-e232-409d-915a-e668e73550be) Gmail in Chrome

![Outlook 2019 (macOS 10.14) .png](https://images.zenhubusercontent.com/5c630d90c95c1c66f2b87ae3/c04e7e33-5cb3-49e0-b257-68511fc9a600) Outlook 2019 (macOS 10.14)

![iPhone 7 (iOS 11.3.1).png](https://images.zenhubusercontent.com/5c630d90c95c1c66f2b87ae3/f087405d-1323-4f74-8454-efd6b407e4b9) iPhone 7 (iOS 11.3.1)

![Screen Shot 2019-03-08 at 10.29.18 AM.png](https://images.zenhubusercontent.com/5c630d90c95c1c66f2b87ae3/f591377b-2f63-45db-976c-afa884b4b68f) How it looks in wherebydesign

**Comment by michaelschofield** [comment]
schoeyfield   [1 minute ago]
I definitely want to add to this ticket that this spacing isn't a component issue ^. It's coming from the LDs.


schoeyfield   [< 1 minute ago]
If we were additional CSS for this it shouldn't be for the outro block, it should be for `p` without a subsequent `p` tag, which requires css like `p + p {}`, which may not work in email clients anyway.
