### ISSUE TITLE
Add checkbox in account settings for members to opt in to receive swag by mail 

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#930]
## Reproduction Steps
new feature 

## Expected Results
When members go to their account settings, they can check a box to opt in to receive their swag by mail

## DOD
When members go to their account settings, they can check a box to opt in to receive their swag by mail. We also need instructions on how Alexandra will find out if they've opted into this.

### Additional information:
 - BTID-459
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recLyK8BPAeqb0AXl) - (may include image attachments)

### Submitted by
Name: 
Email: 
Slack ID: alexandra044

**Comment by michaelschofield** [comment]
## QA 
1. Log in to an account that isn't a member, confirm that there is no mail-swag related checkbox under account details
2. Log in to an account that is a member, confirm that the checkbox appears.
3. Check the box and save. Ensure that when you refresh, or leave then return to the account details this remains set.
