### ISSUE TITLE
Add header fields to non-promo newsletter builder sections

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#938]
## Definition of done
 - LD's are able to add titles to the following sections in distinct CMS fields on production:
   - GREETING (Component 4)
   - WATERCOOLER CONTENT (W/ NO PHOTO) (Component 5)
   - SERIES CONTENT -or- EVERGREEN CONTENT -or- SOCIAL CONTENT (W/ PHOTO) (Component 7)
   - FOR OUR MEMBERS/BECOME A MEMBER (Component 9)
   - CUSTOM CONTENT (W/ PHOTO) published only if sold (Component 11)
   - UPCOMING EVENTS (Component 12)
   - OUR EVENTS/PARTNER EVENTS (Component 13)
   - OUTRO (Component 16) 
 - Titles act as standard card header titles in both email and browser views

## Notes
Anika or someone equivalent should be able to enter all possible section headers in a newsletter settings page. Purpose: make consistent the section titles to avoid confusion

Don't need to worry about this working with wherebyapp

**Comment by kassanj** [comment]
### QA Notes

1. First, you need to sync the ACF fields. 
2. Create a newsletter, fill out all the fields. Save.
3. Check the browser view. 
EXPECT: Displays all content without errors.
4. Send a test email
EXPECT: Displays all content without errors.
5. Check an [old newsletter](https://thenewtropic.com/newsletter/2019-03-18-heres-how-to-score-a-colada-cake/) via the archive.
EXPECT: Displays all content without errors, nothing drastically different from before.

**Comment by michaelschofield** [comment]
@kassanj Everything looks good in emails. In browser, when previewing, I see

![image.png](https://images.zenhubusercontent.com/5907891d51aa2c30577cf4d5/73ce984e-1636-4c66-a9cc-96e4c42fea60)

This is specifically [this newsletter](https://thenewtropic-com.wbu.staging.wpengine.com/wp-admin/post.php?post=84280&action=edit)

**Comment by michaelschofield** [comment]
@kassanj Oops sorry this is probably more related to the _other_ newsletter tix, but I QA'd both at the exact same time. I'll move _the other one_ into ready for release.
