### ISSUE TITLE
LD's select from a fixed number of header titles per newsletter section

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#939]
The problem: Not having consistent headers adds confusion and time to the newsletter writing and editing process. Currently, they must be inputted manually. It's helpful to have our technology match our standards outlined in documentation. Anika believes it will make a huge difference in giving everyone an understanding of the content we make.

Ticket description: Standardize newsletter section header text by adding a dropdown menu of options specific to each section. Someone responsible for updating content taxonomy should be able to enter multiple section titles the LD can choose from at a settings or configuration screen. 

These section titles would be for:
   - WATERCOOLER CONTENT (W/ NO PHOTO) (Component 5)
   - SERIES CONTENT -or- EVERGREEN CONTENT -or- SOCIAL CONTENT -or- CUSTOM CONTENT (W/ PHOTO) (Component 7)

Specifications:
 - If there has not been candidate titles added for that section, the field should default to a blank text field
 - If there has been candidate titles added for that section, the LD should have a way to choose from those titles and have the title pre-filled.

More info here: https://docs.google.com/document/d/1lgnBacxVSNuAADOBnG3YwHantx7gyoTKzFjbBt2yif8/edit?usp=sharing

Note: We probably won't do this until we overhaul our builder

**Comment by carogea** [comment]
Steps it would take to do this:

1. We would have to go into the settings page and then for each component, we would have to create an interface for Anika to add all of the possible section titles 
2. Go into the NL builder and for each component, make a dropdown from those titles to have them choose and if none of them are chosen, just create a textbox like it is right now
3. What about legacy stuff? If we created a dropdown and launched it next week, unclear if we would call it a new field. We would have to build a dropdown to fill the content box.

**Comment by carogea** [comment]
Notes: Worries about the amount of work to make sure it's working well

**Comment by carogea** [comment]
Not moving to sprint backlog right now, may revisit

**Comment by carogea** [comment]
**Purpose:** make consistent the section titles to avoid confusion. Definitely need consistent headers, helpful to have our tech match the standards we have documented. Been an issue for two years. Anika likes Ernie’s idea about building as a setting in the NL builder. Rather than having tech go in and hardcode things, we just need one person responsible for updating the content taxonomy. Would make a huge difference in giving everyone an understanding of the content we make.
