### ISSUE TITLE
Add image and caption fields to non-promo newsletter builder sections

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#940]
## Definition of done
 - LD's are able to add images to the following sections in distinct CMS fields on production:
   - ~GREETING (Component 4)~
   - WATERCOOLER CONTENT (W/ NO PHOTO) (Component 5)
   - SERIES CONTENT -or- EVERGREEN CONTENT -or- SOCIAL CONTENT (W/ PHOTO) (Component 7)
   - FOR OUR MEMBERS/BECOME A MEMBER (Component 9)
   - CUSTOM CONTENT (W/ PHOTO) published only if sold (Component 11)
   - ~UPCOMING EVENTS (Component 12)~
   - ~OUR EVENTS/PARTNER EVENTS (Component 13)~
   - OUTRO (Component 16) 
 - Images and captions act as standard card header images seen in WhereBy.Design in both email and browser views

See also #938

**Comment by carogea** [comment]
We don't want to start NLs with custom content, but some LDs felt that they had to do this. Bad reader experience

**Comment by ErnieAtLYD** [comment]
Updated w/ Feedback from Anika.

**Comment by kassanj** [comment]
### QA Notes

1. First, you need to sync the [ACF fields](https://thenewtropic.com/wp-admin/edit.php?post_type=acf-field-group). 
2. Create a newsletter, fill out all the image fields. Save.
3. Check the browser view. 
EXPECT: Displays all content without errors.
4. Send a test email
EXPECT: Displays all content without errors.
5. Check an [old newsletter](https://thenewtropic.com/newsletter/2019-03-18-heres-how-to-score-a-colada-cake/) via the archive.
EXPECT: Displays all content and images without errors, nothing drastically different from before.
Make sure to check for image caption and credit functionality.

**IMPORTANT**
We need to sync all markets when this is pushed to production
