### ISSUE TITLE
Warn LDs if section content is over a set character limit

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#941]
## Job story
WHEN I'm an LD writing newsletter content
I WANT to be warned if section content is over a preset character limit
BUT still be able to publish/edit the newsletter
SO THAT newsletter content is consistent, matches our documented standards, is easy to read, etc

## Definition of done
- The LD is notified that section(s) are too long before the newsletter is scheduled publishing
- An LD should be able to publish a newsletter, even if content runs too long in a particular area

## Specifications
GREETING (Component 4): No more than 400 characters
WATERCOOLER CONTENT  (Component 5): No more than 1,000 characters
SERIES CONTENT -or- EVERGREEN CONTENT -or- SOCIAL CONTENT (Component 7): No more than 700 characters
FOR OUR MEMBERS/BECOME A MEMBER (Component 9): No more than 700-characters
CUSTOM CONTENT (W/ PHOTO) (Component 11): No more than 700 characters
OUTRO (Component 16): No more than 400 characters

More here: https://docs.google.com/document/d/10XLylHicZpgKmpILCd0FaBcjh8WsKeN08CnLAzvYGdQ/edit?usp=sharing

**Comment by carogea** [comment]
Is this actually solving a problem we have? 

Is she referring to all content in the newsletters or just the headers?

There are a few options for how we could approach this: 
-for each component, build a javascript thing that measures the length of the characters and then either when you focus off the textbook or save a draft or some other task, it does a form validation and then shows warnings. This is ~5 estimate
-There could be a character counter in the wysiwyg editor, and if that's the case, could be as simple as turning it on and having a one sentence callout saying, this shouldn't go over X characters. This is a ~2 or ~3 estimate, if this functionality exists
