### ISSUE TITLE
Standardize markup between individual events in each of the planner sections

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#942]
## Job story
WHEN I'm an LD copying and pasting event listings from Google Docs into the newsletter builder
I WANT the newsletter builder to standardize markup between individual events in each of the planner sections
SO THAT there is a consistent and beautiful way event lists are displayed inside a newsletter

**Comment by ErnieAtLYD** [comment]
Possible consideration: standardizing a newsletter event into its own CMS field e.g., emoji, name, description, link, neighborhood, postscript comment

**Comment by carogea** [comment]
An interesting project bc it's technically a listicle

Schofield: Short term thing is to have them format it properly for now. Real fix is to have them put events into calendar and then pull from there (using event API). As long as their workflow starts in Google Docs, they're going to have to jump through some hoop anyway.

Shortcode is one way to do it but unclear if they will like it. It would mean we don't have to add something to the newsletter builder.

We should table this for now on the tech side, but plan to discuss it further w stakeholders
