### ISSUE TITLE
NL browser view: header_and_content section shows if there is whitespace

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#947]
1. https://pulp.town/newsletter/2019-01-29-take-a-look-at-our-best-side-orlando/
2. Go to `header_and_content` section

Expect for the section to not appear 
Actual is below
![image](https://user-images.githubusercontent.com/33945/54394521-76d76b00-4683-11e9-998e-eaeca4b9f89e.png)

We may need to run the PHP `trim()` function.

**Comment by carogea** [comment]
Looks good
