### ISSUE TITLE
When you save a newsletter as DRAFT it should clear the newsletter ID

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#952]
Reasoning: if people are saving a draft of their newsletters again and the newsletter has not been scheduled yet, it's usually because they want to make an edit to the newsletter, which means they have to recreate the campaign ID for testing.

DOD: When a newsletter is saved as a draft, the campaign ID should be cleared.

- [ ] Take an opportunity to refactor / abstract to NewsletterService (where it makes sense with the code you touch)

**Comment by michaelschofield** [comment]
## QA
1. Create a new newsletter.
2. Send a test email, it should generate a campaign ID and refresh the page.
3. Confirm there is a campaign ID in the field.
4. Make some changes. Hit save.
5. Confirm that the campaign ID is gone.
6. Send a test email again, it should generate a different campaign ID.
7. Schedule for publishing and make sure it goes out.
