### ISSUE TITLE
Add a profile setting to enable users to opt-in to share their full name (and other info) in newsletter content

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#969]
## Reproduction Steps
^

### Additional information:
 - BTID-469
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/rec09vAM4XSwBOUtj) - (may include image attachments)

### Submitted by
Name: Michael Schofield 
Email: michael@whereby.us
Slack ID: michael

**Comment by michaelschofield** [comment]
## QA
1. Log in to your account and confirm a checkbox about letting us use a full name appears
2. Check the box, then save.
3. Refresh / leave and then return. Confirm the box is still checked.
