### ISSUE TITLE
Prepare PIT mailing list for importing

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#998]
* Make an empty Incline mailing list so we can set up all of the static information
* Set up and get it ready for an import
- [x] Set list name
- [x] Form settings
- [x] Set campaign URL
- [x] Day-to-day summary email -- set to news@theincline.com
- [x] Verify domain for news@theincline.com
- [x] Publicity settings
- [x] Email footer reminder text
- [x] Email footer contact name email phone
- [x] Email footer address 
- [x] Input google analytics tracking ID

Set up
- [x] Groups for newsletters
- [x] Groups for stories  
- [ ] Groups for Custom Groups (talk to Lindsey, maybe she doesn’t need these anymore) unclear if we need but we can set up later
- [ ] Set up the audience fields and merge tags (can wait until after)
- [ ] Segments? (will these auto populate when i import?)
- [ ] Tags? (will these auto populate when i import?)
- [x] Webhooks? Don't need
- [ ] List fields

**Comment by carogea** [comment]
Do it Monday
